### ISSUE TITLE
Allow some single-quoted HAML coding styles

### ISSUE THREAD

**Issue by woahdae** [aurels/translation-gem#1]
Currently, using `= _('foo')` and `= _("foo")` work, as well as `=_ "foo"` and `= _"foo"`, but not `=_ 'foo'` nor `= _'foo'`. The latter style won't be picked up, and it took a bit of investigation to figure out why.

https://github.com/aurels/translation-gem/blob/master/lib/translation_io/extractor.rb has a regex that, according to https://www.debuggex.com/r/fYSQ-jwQfTjhhE6T omits these cases.

It would be nice to have these fixed, or document their exclusion. For now, I'll be vigilant in using double-quotes and will put it in my own projects' documentation.

Oh, and thanks for a great service! I'm a very happy new user, otherwise :)

**Comment by MichaelHoste** [comment]
Hi @woahdae, thanks a lot for your feedback!

Our first guess was also that our extractor RegExp (the one that makes us proud and ashamed at the same time :smile:) was not complete, but your examples are actually correctly detected by it.

So we dug and apparently it was an issue with the .rb parsing of Gettext if there are no parenthesis AND if the call is outside of any method. And this is exactly the case when we extract gettext calls from HAML files.

We think we know how to fix it but we need to make more tests, we'll keep you in touch when it will be released in the following days.

Thanks again, we're glad you're a happy user ! :-)

**Comment by MichaelHoste** [comment]
Hi @woahdae, the new 1.4 version of this gem should solve you problem.
If you have time to confirm it, that would be nice, but I already close this issue ;-)

**Comment by woahdae** [comment]
Yep! Confirmed, works as expected. Thanks!
