### ISSUE TITLE
sync is leaving behind yml-e files

### ISSUE THREAD

**Issue by dankohn** [aurels/translation-gem#16]
Hi, running sync leaves my repo with a bunch of odd files:
```bash
$ rake translation:sync
cp -p config/locales/en.yml config/locales/en.yml.ORIG
* Downloading YAML source editions.
* Applying YAML source editions.
* Updating POT file.
* Generating POT file from YAML files.
* Saving new PO files.
* Creating new MO files.
* Saving new translation YAML files.
* Saving new localization YAML files (with non-string values).
* Collecting YAML localization entries

----------
Use this URL to translate: http://translation.io/david-a-wheeler/cii-best-practices-badge
----------
Removing bogus trailing whitespace (bug workaround).
cd config/locales/ && sed -i -e 's/ $//' *.yml && cd ../..
mv config/locales/en.yml.ORIG config/locales/en.yml
Now run: git commit -as -m 'rake translation:sync'
$ git status
 M config/locales/.translation_io
 M config/locales/translation.fr.yml
?? config/locales/en.yml-e
?? config/locales/localization.de.yml-e
?? config/locales/localization.fr.yml-e
?? config/locales/localization.ja.yml-e
?? config/locales/localization.zh-CN.yml-e
?? config/locales/translation.de.yml-e
?? config/locales/translation.fr.yml-e
?? config/locales/translation.ja.yml-e
?? config/locales/translation.zh-CN.yml-e
```
The first two (modified) files are just what I expect. But then all of the `config/locales/*.yml-e` files shouldn't be there. Obviously, I delete them and may add an [additional](https://github.com/linuxfoundation/cii-best-practices-badge/blob/master/lib/tasks/default.rake#L376) sync task to do so automatically.

But I thought I'd report this in case anyone else sees the same thing. I'm on OS X while my colleague on Linux doesn't this issue.

Cc @david-a-wheeler

**Comment by david-a-wheeler** [comment]
This may be because you didn't have the file .translation_io in config/locales. I have since check that file into git, and I hope that fixes it.

**Comment by dankohn** [comment]
I did `git pull` on master before filing the issue and got https://github.com/linuxfoundation/cii-best-practices-badge/blob/master/config/locales/.translation_io so that's not it.

**Comment by MichaelHoste** [comment]
Hi @dankohn,

My guess is that "sed" doesn't behave the same on Linux and MacOS. I use MacOS and when I type `man sed` I can see this:

    -i extension
                 Edit files in-place, saving backups with the specified extension.

And just after `-i` there is `-e` in your example. So that should be the issue here.

I hope it helped.

**Comment by dankohn** [comment]
That totally explains it, thank you.
