### ISSUE TITLE
Gem memory usage

### ISSUE THREAD

**Issue by woahdae** [aurels/translation-gem#2]
I'm looking for ways to reduce the in-memory usage of our app, and noticed translation is half the memory footprint of Rails itself!

Using https://github.com/schneems/derailed_benchmarks on my app, I found:

    translation: 10.9258 MiB
      gettext/tools: 6.9023 MiB
        gettext/tools/msginit: 5.3867 MiB
          locale/info: 4.582 MiB
            locale/info/language: 4.4648 MiB
          gettext/tools/msgmerge: 0.668 MiB (Also required by: gettext/tools)
            text: 0.5313 MiB
        gettext/tools/xgettext: 1.3164 MiB (Also required by: translation_io/railtie)
          gettext/tools/parser/erb: 1.1445 MiB
            gettext/tools/parser/ruby: 1.0977 MiB (Also required by: gettext/tools/xgettext)
              irb/ruby-lex: 1.0039 MiB
                irb/ruby-token: 0.457 MiB
      gettext/po_parser: 2.1328 MiB (Also required by: gettext/tools/msgfmt, gettext/tools/msginit, and 3 others)
      gettext: 0.8828 MiB (Also required by: gettext/tools/xgettext, gettext/tools/parser/glade, and 5 others)
        locale: 0.4336 MiB (Also required by: gettext/tools/xgettext)
          locale/tag: 0.3047 MiB
        gettext/text_domain_manager: 0.4336 MiB (Also required by: translation)
          gettext/text_domain: 0.3867 MiB
      translation_io/client: 0.4961 MiB

For the running app, after it's been translated, is there anything I/we can cut? What is "locale/info/language" (4.4mb) and "gettext/po_parser" (2.1328mb)?

Thanks!

**Comment by MichaelHoste** [comment]
Hi Woody,

Actually we don't have a lot of control over this. Our gem uses Gettext (https://github.com/ruby-gettext/gettext) which relies on Locale (https://github.com/ruby-gettext/locale).

We can try to explain `locale/info/language` by this file that is loaded in memory with a lot (way too much actually!) of languages codes: https://github.com/ruby-gettext/locale/tree/master/lib/locale/data/languages.tab.gz

Once unzipped it is 160Ko but in memory it's certainly way more than that.

`po_parser` is the PO files Parser (you guessed it? ^^). PO files contains all the gettext keys and translations. Maybe it's where the translations are kept in a hash to fast access.

Like we said, there is not much we can do, maybe try to create an issue on Locale about this Language.tab.gz file?

**Comment by woahdae** [comment]
So the `po_parser` is used at runtime, not just when making `.mo` files? If it's not used for runtime translations, it could be required on-demand (of course).

No worries, though. Had to ask.

**Comment by karolsluszniak** [comment]
@MichaelHoste What about a case when only YAML translations are used in the app? Shouldn't gettext be included in `Gemfile` separately only in apps which actually use it (and don't have the `config.disable_gettext = true` in their config)?

I guess it's also possible to include the `translation` gem only in development in the Gemfile.

**Comment by aurels** [comment]
Hi,

Following up to your email from yesterday, we have been working on that today with @MichaelHoste.

The changes are in this branch : 
https://github.com/aurels/translation-gem/tree/dont-load-gettext-if-disabled

What do you think ? Would you try the branch on your projet to give us your thoughts ?
That's not what I call beautiful but I think it should work as expected.

If you wonder why we still include gettext stuff in `tasks.rb`, that's because our API is GetText-based (even for YAML). So GetText would be loaded when running rake tasks but not in the server/console etc.

**Comment by karolsluszniak** [comment]
Thanks for the response. I like those changes.

The only downside is that it won't be possible to sync with your system on CI platforms on which we're running in production env (we were thinking about implementing such flow). Still, it's okay as it's not a scenario that you support and if the API also needs GetText then it simply can't be helped. 

Anyway, I think it's a good solution for all gem users that don't use Gettext. All the extra hoops in the code are well worth it if users won't have to learn where that extra 10 MB went through profiling :)

**Comment by aurels** [comment]
Nice to read it will fit your needs ;-)
Expect it to be in the next gem release, probably next week. We'll close this issue at that time.
In the meantime please continue using the GH branch in your Gemfile ;-)

**Comment by aurels** [comment]
Hi,

I just published a new version of the gem including the changes : 

+ https://rubygems.org/gems/translation/versions/1.8
+ https://github.com/aurels/translation-gem/releases/tag/v1.8
