### ISSUE TITLE
translation:sync misses translations nested inside other strings

### ISSUE THREAD

**Issue by glennfu** [aurels/translation-gem#21]
`_("Word")` gets picked up by the sync, but `"#{_("Word")}"` does not. I tested this in both .rb and .erb files. It seems like this should work.

**Comment by MichaelHoste** [comment]
It's unfortunately a known limitation of the ruby-gettext gem we depend on (https://github.com/ruby-gettext/gettext/issues/42, https://github.com/ruby-gettext/gettext/issues/21, https://github.com/ruby-gettext/gettext/issues/4).

We already tried to fix it ourselves but it seems that the ruby parser used in that gem should go from "ruby_parser" to "ripper" and that's already quite a big change!

The best solution for now is to use something like: 

```
"blabla " + _('word')
```
or
```
word = _('word')
"blabla #{word}"
```

That's something to keep in mind when writing i18n code and even if that's not perfect, we don't think it's worth a complete rewrite of the ruby-gettext gem.
