### ISSUE TITLE
Traditional Chinese not being picked up

### ISSUE THREAD

**Issue by woahdae** [aurels/translation-gem#4]
When translating Spanish, everything seems to be working as expected. When translating to traditional Chinese (zh-Hant), no translations are picked up.

I created a project to repro the issue, but made it private out of general paranoya since the project I extracted it from is private. @aurels has access: https://github.com/InPlay/translation_bug_repro.

Here is the test from the repro project, `traditional_chinese_test.rb`:

    require 'minitest/spec'
    require 'minitest/autorun'
    require 'rails'
    require 'translation'

    TranslationIO.configure do |config|
      config.api_key        = ''
      config.source_locale  = 'en'
      config.target_locales = ['zh-Hant', 'es']
      config.locales_path   = 'gettext'
    end

    describe 'When translating from English' do
      it 'can translate "Sign In" to Spanish' do
        TranslationIO::Proxy.current_locale = 'es'
        TranslationIO::Proxy._("Sign Up").must_equal("Regístrese")
      end

      it 'can translate "Sign In" to Chinese' do
        TranslationIO::Proxy.current_locale = 'zh_Hant'
        TranslationIO::Proxy._("Sign Up").must_equal("報名")
      end
    end

Here's the output from running `ruby traditional_chisese_test.rb` in the repro directory:

    # Running:

    .F

    Finished in 0.007483s, 267.2868 runs/s, 267.2868 assertions/s.

      1) Failure:
    When translating from English#test_0002_can translate "Sign In" to Chinese [traditional_chisese_test.rb:24]:
    Expected: "報名"
      Actual: "Sign Up"

    2 runs, 2 assertions, 1 failures, 0 errors, 0 skips

**Comment by MichaelHoste** [comment]
Hi Woody,

I don't have access to your repository (I'll ask @aurels later) but could it be that changing `TranslationIO::Proxy.current_locale = 'zh_Hant'` to `TranslationIO::Proxy.current_locale = 'zh-Hant'` in your test would resolve this issue?

If not, we'll investigate further and add some tests in our side (some of our users already translate to Chinese and it works, but I'm not sure the target is "zh-Hant" or another one)

**Comment by woahdae** [comment]
When talking to GetText, TranslationIO underscores dashes: https://github.com/aurels/translation-gem/blob/7702ebb2fbb94099d7a3a5f02e9feabb18954a27/lib/translation_io/railtie.rb#L31

I tried it just to see, though, and no luck.

**Comment by woahdae** [comment]
(oh and I gave you access @MichaelHoste)

**Comment by aurels** [comment]
Hi,

After looking deeply into your, our and GetText's code we think we have understood the root of the issue.

1) Something is missing in your test app : MO files need to be regenerated to be taken into account at runtime. In a real-world Rails usage it's done automatically at the end of the sync.

So we need something like this in the test (we have pushed changes on your repo) : 

    TranslationIO::Client::BaseOperation::CreateNewMoFilesStep.new(TranslationIO.config.locales_path).run

2) But it's not all we need to make the test succeed. GetText does not seem to like the `zh_Hant` in the directory name. If we rename the directory to `zh_XX` and use `zh_XX` in the code it picks the correct translations. According to our tests it will only work for patterns like `xx` ou `xx_XX` (with that exact case!).

Looking at this list https://msdn.microsoft.com/ja-jp/goglobal/bb896001(en-us).aspx (which is the one used by Gettext for Ruby) we see that `zh-Hans` is the same as `zh-CN` and `zh-Hant` as `zh-TW`.

also we can read here http://gnu.utils.bug.narkive.com/Fwl98IoA/using-gettext-for-runtime-translations : 

> Note that converting from a IANA language code to a locale name
("de-AT" -> "de_AT") consists not only of changing the '-' to '_'.
You also have to take care of a few special cases, such as
"zh-Hans" -> "zh_CN", "zh-Hant" -> "zh_TW".

So we don't even think both the languages even need to be in the list and we think about removing `zh-Hans` and `zh-Hant`. Only `zh-CH` and `zh-TW` should be available on Translation.io (or people may try to create both and the repertories will clash).

Does that solution makes sense to you ? Or are we missing a subtlety about Chinese variants ?

**Comment by MichaelHoste** [comment]
2 more links about this issue:

 * http://whyprogramming.com/django/520893-Django-How-to-implement-zh-Hans-Chinese
 * https://code.djangoproject.com/ticket/18419

**Comment by woahdae** [comment]
> If we rename the directory to zh_XX and use zh_XX in the code it picks the correct translations.

I pulled your changes, and this does indeed work! Nice.

> Only zh-CH and zh-TW should be available on Translation.io ... Does that solution makes sense to you ? Or are we missing a subtlety about Chinese variants ?

I'm very unqualified to say, all I know about the Chinese variants I read in one Googling session. Our users want "Traditional Chinese," but I honestly don't know what that means exactly.

Facebook's language selector, as a reference, supports "Traditional Chinese (Taiwan), Simplified Chinese (China), Traditional Chinese (Hong Kong)," and I can't say what the difference is.

This seems like a step forward, so I'll take it!

1) Something is missing in your test app : MO files need to be regenerated to be taken into account at runtime.

This seems odd, so I pulled your changes & removed `TranslationIO::Client::BaseOperation::CreateNewMoFilesStep.new(TranslationIO.config.locales_path).run`, and the tests pass. I don't think this is required to get it working.

So, how do I get my account converted from "zh-Hant" to "zh-TW" without losing the translator's work?

**Comment by woahdae** [comment]
(^ oops, errant click)

**Comment by aurels** [comment]
> This seems odd, so I pulled your changes & removed TranslationIO::Client::BaseOperation::CreateNewMoFilesStep.new(TranslationIO.config.locales_path).run, and the tests pass. I don't think this is required to get it working.

That's because the MO file we pushed is already OK ;-)

> So, how do I get my account converted from "zh-Hant" to "zh-TW" without losing the translator's work?

We will be working on that tomorrow. We are not sure what the best solution is yet. We'll let you know ;-)

**Comment by woahdae** [comment]
Ah, I see. The MO files were present originally, and it sounded as if you were saying they were missing, leading to an issue. I'm not surprised that after changing "zh-Hant" to "zh-HA" they needed to be regenerated to pick up the name change as a logistical issue, similar to needing to re-compile after a code change.

Anyways, thanks for being so responsive!

**Comment by MichaelHoste** [comment]
Hi @woahdae, we found the origin of this issue deep in Gettext code. We made a pull request to fix it and we hope it will be merged soon => https://github.com/ruby-gettext/gettext/pull/45

If it's not merged at the end of this week, we'll be considering the "monkey-patch" option, but we hope it will not be needed ;-)

In both the situations, it will work without the need to change anything in your project (except "bundle update translation")

**Comment by MichaelHoste** [comment]
Our pull request was merged into Gettext codebase => https://github.com/ruby-gettext/gettext/pull/45

Now we need to wait for Gettext to release a new version to add it to our gem dependencies... But we're still considering a monkey-path (on tuesday maybe). Is that timeline ok for you? Sorry for the inconvenience

**Comment by MichaelHoste** [comment]
Hi @woahdae,

Gettext released its new version, and we released ours accordingly.
So `bundle update translation` and `rake translation:sync` should make things work for you :-)
Can you confirm it?

Thanks for your help!

**Comment by woahdae** [comment]
Confirmed, this fixes it! Thanks so much!

**Comment by MichaelHoste** [comment]
Nice! Thanks to you for finding this! It was a bad bug deep in our stack :p
